home:
    path: /
    defaults: { _controller: AppBundle:Default:index }
    methods: [ GET ]

catchall:
    path: /{catchall}
    defaults: { _controller: AppBundle:Default:proxy }
    requirements:
        catchall: '.+'
