home:
    path: /
    defaults: { _controller: AppBundle:Default:index }
    methods: [ GET ]

event:
    path: /event
    defaults: { _controller: AppBundle:Default:event }
    methods: [ GET ]

eventLoad:
    path: /eventLoad
    defaults: { _controller: AppBundle:Default:eventLoad }
    methods: [ GET ]

eventproxy:
    path: /eventproxy
    defaults: { _controller: AppBundle:Default:eventProxy }
    methods: [ POST ]